Update plugin_ci.yml

diff --git a/.github/workflows/plugin_ci.yml b/.github/workflows/plugin_ci.yml
--- a/.github/workflows/plugin_ci.yml
+++ b/.github/workflows/plugin_ci.yml
@@ -30,7 +30,7 @@ jobs:
 
       - name: Decrypt keystore
         run: |
-          openssl aes-256-cbc -K ${{ secrets.ENCRYPTED_KEYSTORE_KEY }} -iv ${{ secrets.ENCRYPTED_KEYSTORE_IV }} -in buildKey.jks.enc -out buildKey.jks -d
+          openssl aes-256-cbc -K ${{ secrets.ENCRYPTED_KEYSTORE_KEY }} -iv ${{ secrets.ENCRYPTED_KEYSTORE_IV }} -in buildKey.jks.enc -out buildKey.jks -d || echo "Decrypt key failed"
 
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
